### ISSUE TITLE
Exception: Truth contains unknown token. When I try to train my own data.

### ISSUE THREAD

**Issue by ArtificialZeng** [jungomi/math-formula-recognition#22]
(torch11) ailab@ailab:~/math-formula-recognition-master$ python train.py --prefix "some-name-" -n 200
Running 200 epochs on cpu
Traceback (most recent call last):
  File "/home/ailab/math-formula-recognition-master/dataset.py", line 60, in encode_truth
    index, tok_len = max(matching_starts, key=lambda match: match[1])
ValueError: max() arg is an empty sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 521, in <module>
    main()
  File "train.py", line 444, in main
    gt_train, tokensfile, root=root, crop=options.crop, transform=transformers
  File "/home/ailab/math-formula-recognition-master/dataset.py", line 137, in __init__
    for p, truth in reader
  File "/home/ailab/math-formula-recognition-master/dataset.py", line 137, in <listcomp>
    for p, truth in reader
  File "/home/ailab/math-formula-recognition-master/dataset.py", line 64, in encode_truth
    raise Exception("Truth contains unknown token")
Exception: Truth contains unknown token

**Comment by ArtificialZeng** [comment]
How to label my own data, and train
